CREATE TABLE T_ESPECIALIDADE (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

Insert INTO T_ESPECIALIDADE (nome) VALUES ('Cardiologia');
Insert INTO T_ESPECIALIDADE (nome) VALUES('Pediatria');
Insert INTO T_ESPECIALIDADE (nome) VALUES('Dermatologia');
