CREATE TABLE exame (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
    tipo VARCHAR (50) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;


Insert INTO  medapi.exame (nome, tipo) VALUES ('EXAME 1','TOXICO');